[package]
name = "xscript-examples"
version = "0.0.0"
edition = "2021"
publish = false
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
xscript = { path = "../xscript", features = ["docker", "tokio"] }
